### ISSUE TITLE
Any plan to update?

### ISSUE THREAD

**Issue by Slickdrac** [fauxnik/DerailValleyPersistentJobsMod#20]
Or to fix the issue of Shunting jobs leaving loads on the loading platform and not an Outbound platform?

**Comment by fauxnik** [comment]
> Or to fix the issue of Shunting jobs leaving loads on the loading platform and not an Outbound platform?

This is intentional and will not be changed. Put the cars wherever you see fit after turning in the shunting jobs, or taking the resulting freight haul jobs directly from the loading track.
