### ISSUE TITLE
Steam train bug

### ISSUE THREAD

**Issue by Voidheartd** [fauxnik/DerailValleyPersistentJobsMod#5]
Using 2.0.1 today I noticed that steam trains seem to be bugged with this mod. I was looking for one and found a DE2 instead, with the coal tender attached to it. The mod seems to be causing the steam engine to be replaced with the DE2. I disabled the mod and was able to find a normal steam train.

Have not tried with 2.1

**Comment by nickiaconis** [comment]
I have a hunch at what's going on here. I think the tender doesn't have the `IsLoco` flag set on it (why would it? it's a tender, not a locomotive), and so the mod to preventing it from despawning while the stream locomotive itself is despawning. This likely blocks another steam loco from spawning in its place, and making the DE2 the only loco that can fit.

I'll have to test this theory when I have a free moment at my computer, but if that's the case I think it affects all versions of the mod.

**Comment by fauxnik** [comment]
I have a hunch at what's going on here. I think the tender doesn't have the `IsLoco` flag set on it (why would it? it's a tender, not a locomotive), and so the mod to preventing it from despawning while the stream locomotive itself is despawning. This likely blocks another steam loco from spawning in its place, and making the DE2 the only loco that can fit.

I'll have to test this theory when I have a free moment at my computer, but if that's the case I think it affects all versions of the mod.
