### ISSUE TITLE
Multiple Jobs Target The Same Destination Track

### ISSUE THREAD

**Issue by fauxnik** [fauxnik/DerailValleyPersistentJobsMod#7]
I think there are two things at play here:

1. Using `Environment.TickCount` to seed the random number generator in the `YardTracksOrganizer.GetTrackThatHasEnoughFreeSpace` patch is causing it to select the same track for all jobs with matching available track lists.
2. Skipping track reservation upfront results in multiple jobs being assigned to a track that doesn't have enough room to store the train cars from all the jobs

I think the best way to solve this will be to:

1. During the `JobValidator.ProcessJobOverview` patch, the mod attempts to reserve track space. If the mod takes over more control of this action, it can determine the success or failure of the attempt. If the attempt fails, this means there is not enough space remaining, and the mod can attempt to find a new track.
2. When loading a saved game, track space needs to be reserved for active jobs, but it is currently being skipped.
3. Seed the RNG with a different source to get truly random results.

**Comment by peq123** [comment]
as discussed on discord. I think this expands into shunting and logistic jobs not spawning for completed hauls jobs if there is no space. A potential fix for this is to have the check run on every job completion and assign a job to all all wagons not already associated with one. 

On a slightly separated point, those wagons that aren't associated with a job seem to have their cargo disappear magically after leaving the area. If possible, this should be stopped to maintain true persistence. 

Thanks

Peq123 (Casper)

**Comment by fauxnik** [comment]
Hi @peq123, thanks for chiming in! I agree that the bug you describe should ideally never happen. However, because jobs are assigned based on empty space rather than unreserved space, I don't think it's related to the track targeting issue. I've created #8 to track the bug you describe separately from this one.
